### ISSUE TITLE
Channel map for neuronexus probe Kilosort 4

### ISSUE THREAD

**Issue by ckdc2000** [MouseLand/Kilosort#622]
### Describe the issue:

Hello,
I have just started ussing Kilosort 4 and I have a recording from a Neuronexus probe with 16 channels (A1x16-3mm-100-177) that I want to sort spikes from. I was wondering if the default probe "linear 16x1" is suitable for a recording that was done with this type of neuronexus probe or do I need to create a different channel map for it?

In example probe dictionary page (https://kilosort.readthedocs.io/en/latest/tutorials/make_probe.html), the channels of the 128-channel probe are rectangular but mine are circular with a radius of 7.5 um so I was not sure what to write for xc, yc and the first contact center coordinate. 
Thank you in advance.

**Comment by jacobpennington** [comment]
Hello,
No, the "linear 16x1" map would not work. As for creating your own, Kilosort4 doesn't use any information about the shape or size of the contacts, only the positions of the contact centers. Going off of this diagram from NeuroNexus' catalog:
![image](https://github.com/MouseLand/Kilosort/assets/35777376/745b0a16-a21e-44e2-9d36-09590dbbf053)
It looks like the contacts are spaced 100 microns apart vertically with no lateral variation, so you could use:
'xc': np.ones(16)
'yc': np.ones(16)*100

The positions are all used in a relative way, so the value for the x-coordinates and the first y-coordinate doesn't matter either for sorting.

**Comment by Alchemist-Y** [comment]
@jacobpennington 
Hi, Jacob, I use Neuropixel 2.0 with 4 shanks as my probe, but I find the system-native probe maps only contains the Neuropixel2.0 edition with  1-shank. Based on the tutorial  (https://kilosort.readthedocs.io/en/latest/tutorials/make_probe.html), Could you tell me how to change the parameter 'kcoords' or others to fit this type of probe.
Thanks a lot!

**Comment by jacobpennington** [comment]
@Alchemist-Y I can't give an exact answer, because my understanding is that the data output by those probes is still 385 channels just like Neuropixels 1, so the probe configuration you use will depend on which channels you recorded from. This code will generate xc, yc, and kcoords for all 5120 contacts based on the spec sheet for Neuropixels 2.0, which you'll need to take subsets of based on your setup. I'm also not sure what order the channels are placed in the data, so you might need to adjust chanMap as well.
```
from kilosort.io import save_probe
import numpy as np

# NOTE: THIS WON'T WORK AS-IS! You will need to take subsets of these to get
#       the 384 channels you actually recorded from.
probe = {}

# Specs say 12um square contacts with 32um lateral spacing, 15um vertical spacing,
# 1280 contacts per shank

# Want alternating 6um, 38um for lateral positions
xc0 = np.empty(1280)
xc0[::2] = 6
xc0[1::2] = 38
# Then add 250um for each additional shank
probe['xc'] = np.concatenate([xc0 + (250*i) for i in range(4)])

# For vertical positions, start at 6 and increase by 15
yc0 = (np.arange(640)*15) + 6
# Each position appears twice (two columns on each shank)
yc0 = np.repeat(yc0, 2)
probe['yc'] = np.concatenate([yc0 for i in range(4)])

# Repeat 0 1280 times, then repeat 1 1280 times, etc
probe['kcoords'] = np.repeat(np.arange(4), 1280)

# NOTE: chanMap is just a guess, I don't know which order contacts are placed in
#       the data for Neuropixels 2.
probe['chanMap'] = np.arange(384)
probe['n_chan'] = 384

# Take subsets of xc, yc, kcoords as mentioned above, then save probe.
save_probe(probe, '/some/filepath/probe_name.json')
```

**Comment by Alchemist-Y** [comment]
> @Alchemist-Y I can't give an exact answer, because my understanding is that the data output by those probes is still 385 channels just like Neuropixels 1, so the probe configuration you use will depend on which channels you recorded from. This code will generate xc, yc, and kcoords for all 5120 contacts based on the spec sheet for Neuropixels 2.0, which you'll need to take subsets of based on your setup. I'm also not sure what order the channels are placed in the data, so you might need to adjust chanMap as well.
> 
> ```
> from kilosort.io import save_probe
> import numpy as np
> 
> # NOTE: THIS WON'T WORK AS-IS! You will need to take subsets of these to get
> #       the 384 channels you actually recorded from.
> probe = {}
> 
> # Specs say 12um square contacts with 32um lateral spacing, 15um vertical spacing,
> # 1280 contacts per shank
> 
> # Want alternating 6um, 38um for lateral positions
> xc0 = np.empty(1280)
> xc0[::2] = 6
> xc0[1::2] = 38
> # Then add 250um for each additional shank
> probe['xc'] = np.concatenate([xc0 + (250*i) for i in range(4)])
> 
> # For vertical positions, start at 6 and increase by 15
> yc0 = (np.arange(640)*15) + 6
> # Each position appears twice (two columns on each shank)
> yc0 = np.repeat(yc0, 2)
> probe['yc'] = np.concatenate([yc0 for i in range(4)])
> 
> # Repeat 0 1280 times, then repeat 1 1280 times, etc
> probe['kcoords'] = np.repeat(np.arange(4), 1280)
> 
> # NOTE: chanMap is just a guess, I don't know which order contacts are placed in
> #       the data for Neuropixels 2.
> probe['chanMap'] = np.arange(384)
> probe['n_chan'] = 384
> 
> # Take subsets of xc, yc, kcoords as mentioned above, then save probe.
> save_probe(probe, '/some/filepath/probe_name.json')
> ```

Thanks for your professional solution, which is really a big help！

**Comment by jacobpennington** [comment]
It sounds like this is resolved, so I'm closing this for now. Please let us know if either if you have more trouble getting your probe files set up.

**Comment by jacobpennington** [comment]
@Alchemist-Y Adding this here in case this makes things easier in the future, @jenniferColonell from the Harris lab directed me to this tool for generating .mat probe files to use with Kilosort, with the channel subset already handled. There's a Matlab and python version.
https://github.com/jenniferColonell/SGLXMetaToCoords

**Comment by Alchemist-Y** [comment]
> @Alchemist-Y Adding this here in case this makes things easier in the future, @jenniferColonell from the Harris lab directed me to this tool for generating .mat probe files to use with Kilosort, with the channel subset already handled. There's a Matlab and python version. https://github.com/jenniferColonell/SGLXMetaToCoords
hi Jacob，thanks for your considerable advice. I still have a question: should the order of the coordinate in the probe map keep the same with the .bin recorded data? because in some equipement the recorder system collects the signal in its own order with the headstage, which is different from the contacts order in the probe map. Thanks for your notice and wait for your suggestion.

**Comment by jacobpennington** [comment]
The value at position `i` in `probe['chanMap']` should be the row index `j` in the binary file that corresponds to the data collected from the contact at position `(x = probe['xc'][i], y = probe['yc'][i])` on the physical probe. For example, if I have data like:
```
[[0, 0, 0, 0, ....],
 [2, 2, 2, 2, ....],
 [1, 1, 1, 1, ....],
 [6, 7, 8, 9, ....]]
```
Where the first 3 rows are ephys data and the 4th row is a ground or something else not used for sorting, then my hypothetical linear probe might look like:
```
probe = {
    'xc': [0, 0, 0],
    'yc': [0, 10, 20],
    'chanMap': [0, 2, 1],
    'kcoords': [0, 0, 0],
    'n_chan': 3,
}
```
But it could also look like:
```
probe = {
    'xc': [0, 0, 0],
    'yc': [0, 20, 10],
    'chanMap': [0, 1, 2],
    'kcoords': [0, 0, 0],
    'n_chan': 3,
}
```
You could also think of it as each contact gets a 4-dimensional representation: (x-position, y-position, data index, shank index). In both of those examples, there are three contacts: `(0, 0, 0, 0)` and `(0, 10, 2, 0,)` and `(0, 20, 1, 0)`. It doesn't matter which order they get listed in.

**Comment by Alchemist-Y** [comment]
@jacobpennington Thanks for your clear illustration! I got it.

**Comment by ckdc2000** [comment]
> Hello, No, the "linear 16x1" map would not work. As for creating your own, Kilosort4 doesn't use any information about the shape or size of the contacts, only the positions of the contact centers. Going off of this diagram from NeuroNexus' catalog: ![image](https://private-user-images.githubusercontent.com/35777376/314621612-745b0a16-a21e-44e2-9d36-09590dbbf053.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4OTA2NDAsIm5iZiI6MTcxMTg5MDM0MCwicGF0aCI6Ii8zNTc3NzM3Ni8zMTQ2MjE2MTItNzQ1YjBhMTYtYTIxZS00NGUyLTlkMzYtMDk1OTBkYmJmMDUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDEzMDU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmYWFiYzcyZDAxYmNjZTkzOTNjNDg3ZGRiMWQ4ZGJhNjU3MjFiMGUyODdkNzkwMTk0YmNkYWM4MDAyYTUxNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I4jV7b2BD586YlQY4G26YcYT4GC1laaZzkQ-TP-zMVc) It looks like the contacts are spaced 100 microns apart vertically with no lateral variation, so you could use: 'xc': np.ones(16) 'yc': np.ones(16)*100 (or adjust accordingly if you have more detailed information)
> 
> The positions are all used in a relative way, so the value for the x-coordinates and the first y-coordinate doesn't matter either for sorting.

Thank you very much! I tried to run this script according to your reply:
```
import numpy as np
from kilosort.io import save_probe

chanMap = np.arange(16)
kcoords = np.zeros(16)
n_chan = 16

xc = np.ones(16)
yc = np.ones(16)*100

neuronexus_probe = {
    'chanMap': chanMap,
    'xc': xc,
    'yc': yc,
    'kcoords': kcoords,
    'n_chan': n_chan
}

print(neuronexus_probe)

save_probe(neuronexus_probe, './neuronexus_probe_test.json')
```
However, probe view showed only one channel. Would the correct yc be this: 
`yc = np.array([0 + 100*i for i in range(16)])`
Although, I do not know what the value of the first yc coordinate should be (0 or something else?)
